title: 오픈놀 기술블로그
description: 오픈놀 개발팀의 성장, 기술등을 포스팅한 기술블로그이다.

url: http://openknowl.github.com/openknowl.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: openknowl
   facebook: openknowl
   email: leeyun1533@gmail.com

google_analytics: "UA-58263416-1"
